# Generated by Django 2.1.7 on 2019-03-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieServer', '0002_auto_20190321_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
