# Generated by Django 2.1.7 on 2019-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieServer', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
