# Generated by Django 2.1.7 on 2019-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('actor_1_name', models.CharField(max_length=50)),
                ('actor_2_name', models.CharField(max_length=50)),
                ('actor_3_name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('imdb_score', models.IntegerField()),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
